routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\AttendanceController;
use App\Http\Controllers\AccountController;
use App\Http\Controllers\LoanController;
use App\Http\Controllers\PayrollController;
use App\Http\Controllers\YourProfileController;
use App\Http\Controllers\UserAttendanceController;
use App\Http\Controllers\UserPayrollController;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

 /*
	if 1 page only dont make group
	if multiple page or route please make a group
 */




// Login
Route::get('/', [AuthController::class, 'index'])->name('login');
Route::post('/login', [AuthController::class, 'check_login'])->name('auth.check');
Route::get('/logout', [AuthController::class, 'logoutUser'])->name('auth.logout');

// admin modules
Route::group(['middleware' => ['auth', 'AuthAdmin']], function(){
// admin Dashboard
Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard.index');
Route::get('/dashboard/quote', [DashboardController::class, 'quote'])->name('dashboard.quote');

// Employee management
Route::group(['prefix' => 'employee', 'as' => 'employee.'], function(){
	Route::get('', [EmployeeController::class, 'index'])->name('index');
	Route::get('/add', [EmployeeController::class, 'add'])->name('add');
	Route::post('/update', [EmployeeController::class, 'updateEmployee'])->name('update');
	Route::post('/save', [EmployeeController::class, 'addEmployee'])->name('save');
	Route::get('/past', [EmployeeController::class, 'passEmployee'])->name('pass_employee');
	Route::delete('/delete/{id?}', [EmployeeController::class, 'deleteEmployee'])->name('delete');
	Route::get('/activate/{id?}', [EmployeeController::class, 'activateEmployee'])->name('activate');
	Route::get('/deactivate/{id?}', [EmployeeController::class, 'deactivateEmployee'])->name('deactivate');
});
// Attendance
Route::get('/attendance', [AttendanceController::class, 'index'])->name('attendance');
//loan
Route::get('/loan', [LoanController::class, 'index'])->name('loan');
//payroll
Route::get('/payroll', [PayrollController::class, 'index'])->name('payroll');
});




// User account modules
Route::group(['middleware' => ['auth', 'AuthUser']], function(){
	Route::group(['prefix' => 'account', 'as' => 'account.'], function(){
		Route::get('', [AccountController::class, 'index'])->name('index');
	});

//your profile controller
Route::group(['prefix' => 'user/profile', 'as' => 'user/profile.'], function(){
		Route::get('', [YourProfileController::class, 'index'])->name('index');
	});
//user attendance
Route::group(['prefix' => 'user/attendance', 'as' => 'user/attendance.'], function(){
		Route::get('', [UserAttendanceController::class, 'index'])->name('index');
		Route::get('list', [UserAttendanceController::class, 'list'])->name('list');
		Route::get('insert', [UserAttendanceController::class, 'insert'])->name('insert');
		Route::post('timeInAm/', [UserAttendanceController::class, 'timeInAm'])->name('timeInAm');
		Route::post('timeOutAm/', [UserAttendanceController::class, 'timeOutAm'])->name('timeOutAm');
		Route::post('timeInPm/', [UserAttendanceController::class, 'timeInPm'])->name('timeInPm');
		Route::post('timeOutPm/', [UserAttendanceController::class, 'timeOutPm'])->name('timeOutPm');
		Route::get('outdoorList/{id?}', [UserAttendanceController::class, 'outdoorList'])->name('outdoorList');
		Route::get('outdoorTimeOut', [UserAttendanceController::class, 'outdoorTimeOut'])->name('outdoorTimeOut');
		Route::get('outdoorTimeOut', [UserAttendanceController::class, 'outdoorTimeOut'])->name('outdoorTimeOut');
		Route::get('editOutdoorTimeOut', [UserAttendanceController::class, 'editOutdoorTimeOut'])->name('editOutdoorTimeOut');
		Route::get('editOutdoorTimeIn', [UserAttendanceController::class, 'editOutdoorTimeIn'])->name('editOutdoorTimeIn');
		Route::get('outdoorReason', [UserAttendanceController::class, 'outdoorReason'])->name('outdoorReason');
		Route::post('workplace', [UserAttendanceController::class, 'workPlace'])->name('workplace');
		Route::post('addReport', [UserAttendanceController::class, 'addReport'])->name('addreport');
		Route::post('addReason', [UserAttendanceController::class, 'addreason'])->name('addreason');

	});
//user payroll
Route::group(['prefix' => 'user/payroll', 'as' => 'user/payroll.'], function(){
		Route::get('', [UserPayrollController::class, 'index'])->name('index');
	});



});

resources/views/Layout/admin_navbar.blade.php
<!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-dark navbar-dark">
     <!-- Preloader -->
  
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <!-- <a href="index3.html" class="nav-link">Home</a> -->
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <!-- <a href="#" class="nav-link">Contact</a> -->
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item">
        <a href="{{ route('auth.logout')}}">
        <button type="button" class="btn btn-secondary">Logout</button>
        </a>
      </li>
      
    </ul>
  </nav>
  <!-- /.navbar -->

resources/views/Layout/admin_sidebar.blade.php
<!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
      <img src="{{ asset('img/logo.png')}}" alt="AdminLTE Logo" class="" style=" width: 50px; height: 50px">
      <span class="brand-text text-warning">Brain IT Consultancy</span>
    </a>
    <!-- Sidebar -->
    <div class="sidebar ">
      <!-- Sidebar user panel (optional) -->
      <!-- SidebarSearch Form -->
      <div class="form-inline mt-4">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div>
      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item">
            <a href="{{ route('dashboard.index')}}" class="nav-link">
              <i class="fas fa-tachometer-alt"></i>
              <p style="margin-left: 14px">
                Dashboard
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="fa-solid fa-users"></i>
              <p style="margin-left: 10px">
                Employee
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{{ route('employee.add')}}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Add Employee</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{ route('employee.index')}}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Current Employee</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{ route('employee.pass_employee') }}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Past Employee</p>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <a href="{{ route('attendance') }}" class="nav-link">
              <i class="fas fa-clipboard-user"></i>
              <p style="margin-left: 18px">
                Attendance
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('loan') }}" class="nav-link">
             <i class="fas fa-hand-holding-usd"></i>
              <p style="margin-left: 14px">
                Loan
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('payroll') }}" class="nav-link">
              <i class="fas fa-file-invoice"></i>
              <p style="margin-left: 20px">
                Payroll
              </p>
            </a>
          </li> 
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

resources/views/Layout/app_admin.blade.php
<!DOCTYPE html>
<html>
	<head>
		<title>@yield('title')</title>
		@include('Layout.header')
		@yield('css')
	</head>

	<body class="hold-transition sidebar-mini layout-fixed" style="background-color: #FFF8DC">
		<!-- <div class="preloader flex-column justify-content-center align-items-center">
    <img class="animation__wobble" src="{{ asset('img/logo.png')}}" alt="AdminLTELogo" height="250" width="250">
  </div> -->

			@include('Layout.admin_sidebar')
			@include('Layout.admin_navbar')
			
			@yield('content')
	</body>
	@include('Layout.footer')
	@yield('script')
</html>

resources/views/Layout/app_auth.blade.php
<!DOCTYPE html>
<html>
	<head>
		<title>@yield('title')</title>
		@include('Layout.header')
		@yield('css')
	</head>

	<body style="background-color: #F8F8FF">
			@include('Layout.auth_navbar')
			
			@yield('content')
	</body>
	@include('Layout.footer')
	@yield('script')
</html>

resources/views/Layout/app_user.blade.php
<!DOCTYPE html>
<html>
	<head>
		<title>@yield('title')</title>
		@include('Layout.header')
		@yield('css')
	</head>

	<body class="hold-transition sidebar-mini layout-fixed">
  <div class="preloader flex-column justify-content-center align-items-center">
    <img class="animation__wobble" src="{{ asset('img/logo.png')}}" alt="AdminLTELogo" height="250">
  </div>

			@include('Layout.user_sidebar')
			@include('Layout.user_navbar')
			
			@yield('content')
	</body>
	@include('Layout.footer')
	@yield('script')
</html>

resources/views/Layout/auth_navbar.blade.php
<!-- Navbar -->
  <nav class="navbar navbar-expand navbar-dark navbar-dark">
    <!-- Left navbar links -->
    <!-- Preloader -->
  <div class="preloader flex-column justify-content-center align-items-center">
    <img class="animation__wobble" src="{{ asset('img/logo.png')}}" alt="AdminLTELogo" height="250" width="250">
  </div>
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link h4 pb-0" href="#" role="button">BNJ<span class="text-orange">Santiago</span></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <!-- <a href="index3.html" class="nav-link">Home</a> -->
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <!-- <a href="#" class="nav-link">Contact</a> -->
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item">
      </li>
      
    </ul>
  </nav>
  <!-- /.navbar -->

resources/views/Layout/bread.blade.php
@php $i = 0; $total = count($data); @endphp
@php $link = route('dashboard.index') @endphp
<div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0">{{ $title }}</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item active" aria-current="page"><a href="{{ $link }}">Home</a></li>
            @foreach($data as $key => $val)
              @php $i++;  @endphp
                @if($i == $total && $total != 1)
                   <li class="breadcrumb-item active" aria-current="page">{{ $key }}</li>
                @elseif($total == 1)
                  <li class="breadcrumb-item active" aria-current="page">{{ $key }}</li>
                @else
                    <li class="breadcrumb-item"><a href="{{ $val }}">{{ $key }}</a></li>
                @endif
            @endforeach
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>

resources/views/Layout/footer.blade.php
<!-- jQuery -->
<script src="{{ asset('plugins/jquery/jquery.min.js')}}"></script>
<script type="text/javascript" src="{{ asset('js/ajaxsetup.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/sweetalert.min.js') }}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{ asset('plugins/jquery-ui/jquery-ui.min.js')}}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->

<!-- Bootstrap 4 -->
<script src="{{ asset('plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<!-- ChartJS -->
<script src="{{ asset('plugins/chart.js/Chart.min.js')}}"></script>
<!-- Sparkline -->
<script src="{{ asset('plugins/sparklines/sparkline.js')}}"></script>
<!-- JQVMap -->
<script src="{{ asset('plugins/jqvmap/jquery.vmap.min.js')}}"></script>
<script src="{{ asset('plugins/jqvmap/maps/jquery.vmap.usa.j')}}s"></script>
<!-- jQuery Knob Chart -->
<script src="{{ asset('plugins/jquery-knob/jquery.knob.min.js')}}"></script>
<!-- daterangepicker -->
<script src="{{ asset('plugins/moment/moment.min.js')}}"></script>
<script src="{{ asset('plugins/daterangepicker/daterangepicker.js')}}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{{ asset('plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js')}}"></script>
<!-- Summernote -->
<script src="{{ asset('plugins/summernote/summernote-bs4.min.js')}}"></script>
<!-- overlayScrollbars -->
<script src="{{ asset('plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('dist/js/adminlte.js')}}"></script>
<script type="text/javascript" src="{{ asset('js/main.js') }}"></script>

resources/views/Layout/header.blade.php
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="csrf-token" content="{{ csrf_token() }}">
<title>AdminLTE 3 | Dashboard</title>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" />

<link rel="stylesheet" type="text/css" href="{{ asset('css/animate.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('css/sweetalert.css') }}">
<!-- Google Font: Source Sans Pro -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
<!-- Font Awesome -->
<link rel="stylesheet" href="{{ asset('plugins/fontawesome-free/css/all.min.css')}}">
<!-- Ionicons -->
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<!-- Tempusdominus Bootstrap 4 -->
<link rel="stylesheet" href="{{ asset('plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css')}}">
<!-- iCheck -->
<link rel="stylesheet" href="{{ asset('plugins/icheck-bootstrap/icheck-bootstrap.min.css')}}">
<!-- JQVMap -->
<link rel="stylesheet" href="{{ asset('plugins/jqvmap/jqvmap.min.css')}}">
<!-- Theme style -->
<link rel="stylesheet" href="{{ asset('dist/css/adminlte.min.css')}}">
<!-- overlayScrollbars -->
<link rel="stylesheet" href="{{ asset('plugins/overlayScrollbars/css/OverlayScrollbars.min.css')}}">
<!-- Daterange picker -->
<link rel="stylesheet" href="{{ asset('plugins/daterangepicker/daterangepicker.css')}}">
<!-- summernote -->
<link rel="stylesheet" href="{{ asset('plugins/summernote/summernote-bs4.min.css')}}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />

resources/views/Layout/user_navbar.blade.php
<!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-dark navbar-dark">
    <!-- Preloader -->
  <div class="preloader flex-column justify-content-center align-items-center">
    <img class="animation__wobble" src="{{ asset('img/logo.png')}}" alt="AdminLTELogo" height="250" width="250" style="margin-left: 250px">
  </div>
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button" data-auto-collapse-size="15000"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <!-- <a href="index3.html" class="nav-link">Home</a> -->
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <!-- <a href="#" class="nav-link">Contact</a> -->
      </li>
    </ul>
    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item">
        <a href="{{ route('auth.logout')}}">
        <button type="button" class="btn btn-secondary">Logout</button>
        </a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

resources/views/Layout/user_sidebar.blade.php
<!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-3">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
      <img src="{{ asset('img/logo.png')}}" alt="AdminLTE Logo" class="" style=" width: 50px; height: 50px">
      <span class="brand-text text-warning">Brain IT Consultancy</span>
    </a>
    <!-- Sidebar -->
    <div class="sidebar ">
      <!-- Sidebar user panel (optional) -->
      <!-- SidebarSearch Form -->
      <div class="form-inline mt-4">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div>
      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item">
            <a href="{{ route('account.index')}}" class="nav-link {{ (request()->is('account')) ? 'bg-secondary' : '' }}">
              <i class="fas fa-tachometer-alt"></i>
              <p style="margin-left: 14px">
                Dashboard
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('user/profile.index') }}" class="nav-link  {{ (request()->is('user/profile')) ? 'bg-secondary' : '' }}">
              <i class="fas fa-user"></i>
              <p style="margin-left: 18px">
                Your Profile
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('user/attendance.index') }}" class="nav-link">
             <i class="fas fa-clipboard-list"></i>
              <p style="margin-left: 20px">
                Attendance
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('user/payroll.index') }}" class="nav-link">
              <i class="fas fa-file-invoice"></i>
              <p style="margin-left: 20px">
                Payroll
              </p>
            </a>
          </li> 
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>