routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\AttendanceController;
use App\Http\Controllers\AccountController;
use App\Http\Controllers\LoanController;
use App\Http\Controllers\PayrollController;
use App\Http\Controllers\YourProfileController;
use App\Http\Controllers\UserAttendanceController;
use App\Http\Controllers\UserPayrollController;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

 /*
	if 1 page only dont make group
	if multiple page or route please make a group
 */




// Login
Route::get('/', [AuthController::class, 'index'])->name('login');
Route::post('/login', [AuthController::class, 'check_login'])->name('auth.check');
Route::get('/logout', [AuthController::class, 'logoutUser'])->name('auth.logout');

// admin modules
Route::group(['middleware' => ['auth', 'AuthAdmin']], function(){
// admin Dashboard
Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard.index');
Route::get('/dashboard/quote', [DashboardController::class, 'quote'])->name('dashboard.quote');

// Employee management
Route::group(['prefix' => 'employee', 'as' => 'employee.'], function(){
	Route::get('', [EmployeeController::class, 'index'])->name('index');
	Route::get('/add', [EmployeeController::class, 'add'])->name('add');
	Route::post('/update', [EmployeeController::class, 'updateEmployee'])->name('update');
	Route::post('/save', [EmployeeController::class, 'addEmployee'])->name('save');
	Route::get('/past', [EmployeeController::class, 'passEmployee'])->name('pass_employee');
	Route::delete('/delete/{id?}', [EmployeeController::class, 'deleteEmployee'])->name('delete');
	Route::get('/activate/{id?}', [EmployeeController::class, 'activateEmployee'])->name('activate');
	Route::get('/deactivate/{id?}', [EmployeeController::class, 'deactivateEmployee'])->name('deactivate');
});
// Attendance
Route::get('/attendance', [AttendanceController::class, 'index'])->name('attendance');
//loan
Route::get('/loan', [LoanController::class, 'index'])->name('loan');
//payroll
Route::get('/payroll', [PayrollController::class, 'index'])->name('payroll');
});




// User account modules
Route::group(['middleware' => ['auth', 'AuthUser']], function(){
	Route::group(['prefix' => 'account', 'as' => 'account.'], function(){
		Route::get('', [AccountController::class, 'index'])->name('index');
	});

//your profile controller
Route::group(['prefix' => 'user/profile', 'as' => 'user/profile.'], function(){
		Route::get('', [YourProfileController::class, 'index'])->name('index');
	});
//user attendance
Route::group(['prefix' => 'user/attendance', 'as' => 'user/attendance.'], function(){
		Route::get('', [UserAttendanceController::class, 'index'])->name('index');
		Route::get('list', [UserAttendanceController::class, 'list'])->name('list');
		Route::get('insert', [UserAttendanceController::class, 'insert'])->name('insert');
		Route::post('timeInAm/', [UserAttendanceController::class, 'timeInAm'])->name('timeInAm');
		Route::post('timeOutAm/', [UserAttendanceController::class, 'timeOutAm'])->name('timeOutAm');
		Route::post('timeInPm/', [UserAttendanceController::class, 'timeInPm'])->name('timeInPm');
		Route::post('timeOutPm/', [UserAttendanceController::class, 'timeOutPm'])->name('timeOutPm');
		Route::get('outdoorList/{id?}', [UserAttendanceController::class, 'outdoorList'])->name('outdoorList');
		Route::get('outdoorTimeOut', [UserAttendanceController::class, 'outdoorTimeOut'])->name('outdoorTimeOut');
		Route::get('outdoorTimeOut', [UserAttendanceController::class, 'outdoorTimeOut'])->name('outdoorTimeOut');
		Route::get('editOutdoorTimeOut', [UserAttendanceController::class, 'editOutdoorTimeOut'])->name('editOutdoorTimeOut');
		Route::get('editOutdoorTimeIn', [UserAttendanceController::class, 'editOutdoorTimeIn'])->name('editOutdoorTimeIn');
		Route::get('outdoorReason', [UserAttendanceController::class, 'outdoorReason'])->name('outdoorReason');
		Route::post('workplace', [UserAttendanceController::class, 'workPlace'])->name('workplace');
		Route::post('addReport', [UserAttendanceController::class, 'addReport'])->name('addreport');
		Route::post('addReason', [UserAttendanceController::class, 'addreason'])->name('addreason');

	});
//user payroll
Route::group(['prefix' => 'user/payroll', 'as' => 'user/payroll.'], function(){
		Route::get('', [UserPayrollController::class, 'index'])->name('index');
	});



});

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Models\User;
use Validator;

class EmployeeController extends Controller
{
    public function index(){
    	$users = User::where('user_type', 2)->where('user_status', 'active')->get();
    	
    	return view('Employee.index', compact('users'));
    }

    public function add(){
    	return view('Employee.add');
    }

    public function addEmployee(Request $request){
		$last_name = $request->get('last_name');
		$middle_name = $request->get('middle_name');
		$first_name = $request->get('first_name');
		$birth_date = $request->get('birth_date');
		$date_employed = $request->get('date_employed');
		$gender = $request->get('gender');
		$employment_status = $request->get('employment_status');
		$address = $request->get('address');
		$email_address = $request->get('email_address');
		$password = $request->get('password');
		$confirm_pass = $request->get('confirm_pass');
		$user_img = $request->get('user_img');
		$ec_name = $request->get('ec_name');
		$ec_address = $request->get('ec_address');
		$ec_contact = $request->get('ec_contact');
		$ec_relation_to = $request->get('ec_relation_to');
	    $validator = Validator::make($request->all(), [
	            'last_name' => 'required',
	            'middle_name' => 'required',
	            'first_name' => 'required',
	            'birth_date' => 'required',
	            'date_employed' => 'required',
	            'gender' => 'required',
	            'employment_status' => 'required',
	            'address' => 'required',
	            'email_address' => 'required',
	            'password' => 'required',
	            'confirm_pass' => 'required|same:password',
	            'ec_name' => 'required',
	            'ec_address' => 'required',
	            'ec_contact' => 'required',
	            'ec_relation_to' => 'required'
	        ]);

	        if ($validator->fails()) {
	        	return response()->json(['status' => false, 'error' => $validator->errors()]);
	        }else{
	        	if (!empty($request->file('user_img'))) {
	        		$user = new User;
	        		$user->last_name = $last_name;
	        		$user->middle_name = $middle_name;
	        		$user->first_name = $first_name;
	        		$user->birth_date = $birth_date;
	        		$user->date_employed = $date_employed;
	        		$user->gender = $gender;
	        		$user->employment_status = $employment_status;
	        		$user->address = $address;
	        		$user->email_address = $email_address;
	        		$user->password = $password;
	        		$user->ec_name = $ec_name;
	        		$user->ec_address = $ec_address;
	        		$user->ec_contact = $ec_contact;
	        		$user->ec_relation_to = $ec_relation_to;
	        		$user->user_img = $productsData['user_img'] = $request->file('user_img')->store('user_img','public');
        		if ($user->save()) {
        			return response()->json(['status' => true, 'message' => 'Employee Added Successfully!']);
        			
        		}
	        	}else{
        			return response()->json(['status' => false, 'message' => 'Employee Image is required!']);

	        	}
	        }
   		}

    public function passEmployee(){
    	$users = User::where('user_type', 2)->where('user_status', 'deactive')->get();

    	return view('Employee.past_employee', compact('users'));
    }
    public function updateEmployee(Request $request){
		$user_id = $request->get('user_id');
		$last_name = $request->get('last_name');
		$last_name = $request->get('last_name');
		$middle_name = $request->get('middle_name');
		$first_name = $request->get('first_name');
		$birth_date = $request->get('birth_date');
		$date_employed = $request->get('date_employed');
		$gender = $request->get('gender');
		$employment_status = $request->get('employment_status');
		$employee_position = $request->get('employee_position');
		$address = $request->get('address');
		$email_address = $request->get('email_address');
		$ec_name = $request->get('ec_name');
		$ec_relation_to = $request->get('ec_relation_to');
		$ec_contact = $request->get('ec_contact');
		$ec_address = $request->get('ec_address');
		$user_img = $request->get('user_img');

	$validator = Validator::make($request->all(), [
            'user_id' => 'required',
            'last_name' => 'required',
            'middle_name' => 'required',
            'first_name' => 'required',
            'birth_date' => 'required',
            'date_employed' => 'required',
            'gender' => 'required',
            'employment_status' => 'required',
            'employee_position' => 'required',
            'address' => 'required',
            'email_address' => 'required',
            'ec_name' => 'required',
            'ec_relation_to' => 'required',
            'ec_contact' => 'required',
            'ec_address' => 'required'
        ]);
		if ($validator->fails()) {
			return response()->json(['status' => false, 'error' => $validator->errors()]);
		}else{
			$user = User::where('id', $user_id)->first();
			$user->last_name = $last_name;
			$user->middle_name = $middle_name;
			$user->first_name = $first_name;
			$user->birth_date = $birth_date;
			$user->date_employed = $date_employed;
			$user->gender = $gender;
			$user->employment_status = $employment_status;
			$user->employee_position = $employee_position;
			$user->address = $address;
			$user->email_address = $email_address;
			$user->ec_name = $ec_name;
			$user->ec_relation_to = $ec_relation_to;
			$user->ec_contact = $ec_contact;
			$user->ec_address = $ec_address;
			if (!empty($request->file('user_img'))) {
	        	$user->user_img = $productsData['user_img'] = $request->file('user_img')->store('user_img','public');
			}
			if ($user->save()) {
				return response()->json(['status' => true, 'message' => 'Employee Updated Successfully']);
			}
		}
	}

	public function deactivateEmployee($id){
		$user = User::where('id', $id)->first();
		$user->user_status = 'deactive';
		
		if ($user->save()) {
			return response()->json(['status' => true, 'message' => 'Employee Deactivated Successfully!']);
		}
		}

	public function activateEmployee($id){
		$user = User::where('id', $id)->first();
		$user->user_status = 'active';

		if ($user->save()) {
			return response()->json(['status' => true, 'message' => 'Employee Activated Successfully!']);
		}
	}

	public function deleteEmployee($id){
		$user = User::find($id)->delete();
		return response()->json(['status' => true, 'message' => 'Employee Deleted Successfully!']);
	}
	
}

resources/views/Employee/add.blade.php
@extends('Layout.app_admin')
@section('title', 'Admin Dashboard')
@section('content')

<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
   @include('Layout.bread', ['title' => 'Add Employee', 'data' => ['Add Employee' => '']])
    <!-- /.content-header -->
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-12">
          <form action="{{ route('employee.save')}}" id="add_form" enctype="multipart/form-data" novalidate="" class="needs-validation">
            <div class="card">
              <div class="card-header h4 text-light" style="background: #343A40">Fill out the form below</div>
              <div class="card-body">
                <div class="row">
                  <div class="col-sm-4 form-group mb-3">
                    <label>Lastname</label>
                    <input type="text" name="last_name" id="last_name" class="form-control" placeholder="Enter lastname">
                    <div class="invalid-feedback" id="err_last_name"></div>
                  </div>
                  <div class="col-sm-4 form-group mb-3">
                    <label>Middlename</label>
                    <input type="text" name="middle_name" id="middle_name" class="form-control" placeholder="Enter middlename">
                    <div class="invalid-feedback" id="err_middle_name"></div>
                  </div>
                  <div class="col-sm-4 form-group mb-3">
                    <label>Firstname</label>
                    <input type="text" name="first_name" id="first_name" class="form-control" placeholder="Enter firstname">
                    <div class="invalid-feedback" id="err_first_name"></div>
                  </div>
                  <div class="col-sm-6 form-group mb-3">
                    <label>Birthdate</label>
                    <input type="date" name="birth_date" id="birth_date" class="form-control" placeholder="Enter birthdate">
                    <div class="invalid-feedback" id="err_birth_date"></div>
                  </div>
                  <div class="col-sm-6 form-group mb-3">
                    <label>Date Employed</label>
                    <input type="date" name="date_employed" id="date_employed" class="form-control" placeholder="Enter Date Employed">
                    <div class="invalid-feedback" id="err_date_employed"></div>
                  </div>
                   <div class="col-sm-6 form-group mb-3">
                    <label>Gender</label>
                    <select name="gender" id="gender" class="form-control">
                      <option value="" selected="" disabled="">Select Gender</option>
                      <option value="Male">Male</option>
                      <option value="Female">Female</option>
                    </select>
                    <div class="invalid-feedback" id="err_gender"></div>
                  </div>
                  <div class="col-sm-6 form-group mb-3">
                    <label>Employment Status</label>
                    <select name="employment_status" id="employment_status" class="form-control">
                      <option value="" selected="" disabled="">Select Employment status</option>
                      <option value="Regular">Regular</option>
                      <option value="Trainee">Trainee</option>
                    </select>
                    <div class="invalid-feedback" id="err_employment_status"></div>   
                  </div>
                  <div class="col-sm-12 form-group mb-3">
                    <label>Address</label>
                    <textarea class="form-control" id="address" name="address" placeholder="Enter Full Address here" rows="4"></textarea>
                    <div class="invalid-feedback" id="err_address"></div>  <hr> 
                  </div>
                  <div class="col-sm-12 form-group mb-3">
                    <label>Email</label>
                    <input type="text" name="email_address" id="email_address" class="form-control" placeholder="Enter Email">
                    <div class="invalid-feedback" id="err_email_address"></div>  
                  </div>
                  <div class="col-sm-12 form-group mb-3">
                    <label>Password</label>
                    <input type="Password" name="password" id="password" class="form-control" placeholder="Enter password">
                    <div class="invalid-feedback" id="err_password"></div> 
                  </div>
                  <div class="col-sm-12 form-group mb-3">
                    <label>Confirm Password</label>
                    <input type="password" name="confirm_pass" id="confirm_pass" class="form-control" placeholder="Confirm password">
                    <div class="invalid-feedback" id="err_confirm_pass"></div> 
                  </div>
                  <div class="col-sm-12 form-group">
                    <label>Upload Profile Image</label>
                    <input type="File" name="user_img" id="user_img" class="form-control-file border">
                    <div class="invalid-feedback" id="err_user_img"></div> 
                    <hr>
                  </div>
                  <div class="col-sm-12 form-group text-center">
                    <label class="h5">------- Emergency Contact -------</label>
                  </div>
                  <div class="col-sm-12 form-group">
                    <label>Full Name</label>
                    <input type="text" name="ec_name" id="ec_name" class="form-control" placeholder="Enter Fullname here">
                    <div class="invalid-feedback" id="err_ec_name"></div> 
                  </div>
                  <div class="col-sm-6 form-group">
                    <label>Relationship to employee</label>
                    <input type="text" name="ec_relation_to" id="ec_relation_to" class="form-control" placeholder="Enter Relation to employee">
                    <div class="invalid-feedback" id="err_ec_relation_to"></div> 
                  </div>
                  <div class="col-sm-6 form-group">
                    <label>Contact Number</label>
                    <input type="text" name="ec_contact" id="ec_contact" class="form-control" placeholder="Enter Contact here">
                    <div class="invalid-feedback" id="err_ec_contact"></div> 

                  </div>
                  <div class="col-sm-12 form-group">
                    <label>Address</label>
                    <textarea name="ec_address" id="ec_address" class="form-control" placeholder="Enter Address here" rows="4"></textarea>
                    <div class="invalid-feedback" id="err_ec_address"></div> 
                  </div>
                </div>
              </div>
              <div class="card-footer text-right text-light" style="background: #343A40">
                <button type="button" class="px-4 btn btn-secondary" id="clear_btn">clear</button>
                <button type="submit" class="px-4 btn btn-success" id="save_button">Save</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
@endsection
@section('script')
<script type="text/javascript">
  $('#clear_btn').on('click', function(){
  $('#add_form')[0].reset();
  });


  $('#add_form').on('submit', function(e){
  e.preventDefault();
  // let formData = $(this).serialize();
  let form = $("#add_form")[0];
    // Create an FormData object 
  var data = new FormData(form);
  let url = $(this).attr('action');
  $.ajax({
      type:"POST",
      url:url,
      data:data,
      enctype: 'multipart/form-data',
      processData: false,  // Important!
      contentType: false,
      dataType:'json',
      beforeSend:function(){
      },
      success:function(response){
         //console.log(response);
       if (response.status === true) {
          swal("Success", response.message, "success");
          $('#add_form')[0].reset();
       }else{
          swal("error", response.message, "error");
        showValidator(response.error,'add_form');
        console.log(response);
       }
      },
      error: function(error){
        console.log(error);
      }
    });

});
</script>
@endsection